spring:
  application:
    name: Gateway

  cloud:
    gateway:
      routes:
        - id: r_clients
          uri: http://localhost:8088
          predicates:
            - Path=/clients/**

        - id: r_voitures
          uri: lb://SERVICE-VOITURE   # utilisation de Eureka
          predicates:
            - Path=/voitures/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

server:
  port: 8888
